routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Route::get('/login/{clientid?}', 'Auth\LoginController@showLoginForm')
    ->name('login');

Route::post('/auth', 'Auth\LoginController@login')
    ->name('auth');

Route::get('/logout', 'Auth\LoginController@logout')
    ->name('logout');


Route::get('/forgot', 'Auth\ResetPinController@showForgotPinForm');

Route::post('/forgot', 'Auth\ResetPinController@resetPin')
      ->name('reset_pin');
      
Route::get('/forgot', function () {
    return view('auth.forgot');
});


Route::group(['middleware' => 'auth'],function () {

    Route::get('/dashboard', 'DashboardController@index')
    ->name('dashboard');

     Route::get('/dashboard/email', 'DashboardController@showAddEmail')
    ->name('emai_address_add_form');


     Route::post('/dashboard/email/save', 'DashboardController@saveEmailAddress')
    ->name('emai_address_add');

     Route::get('/email-list', 'DashboardController@emailList')
    ->name('emai_address_list');

    Route::get('/edit-client', 'DashboardController@editClient')
    ->name('edit_client');

     Route::post('/dashboard/client/edit', 'DashboardController@updateClient')
    ->name('update_client');




});


Route::group(['middleware' => 'auth', 'prefix' => 'jobs'],function () {

     Route::get('/create', 'JobsController@show')
    ->name('job_modal');

     Route::post('/', 'JobsController@create')
    ->name('job_create');

	Route::get('/', 'JobsController@lists')
    ->name('jobs_list');

   

    Route::get('/{id}/edit', 'JobsController@edit')
    ->name('job_edit');

     Route::post('/{id}/edit', 'JobsController@update')
    ->name('job_update');

    Route::get('/{category}/{id}', 'JobsController@view')
        ->name('jobs_view');

   Route::post('/attachments', 'AttachmentController@upload')
    ->name('job_attachments');

   Route::post('/attachments/delete', 'AttachmentController@remove')
    ->name('job_attachments_remove');


 Route::post('/save-comment/{id}', 'JobsController@saveComment')
    ->name('save_comment');

       Route::post('/log-work', 'JobsController@logWork')
    ->name('log_work');

});

Route::group(['middleware' => 'auth', 'prefix' => 'task'],function () {

    Route::get('/view/{id}', 'TasksController@view')
        ->name('task_view');

    Route::get('/{category}', 'TasksController@show')
    ->name('task_modal');

   Route::post('/', 'TasksController@create')
    ->name('task_create');

    Route::get('/{id}/delete', 'JobsController@delete')
    ->name('task_delete_model');

    Route::post('/{id}/delete', 'JobsController@remove')
    ->name('task_delete');


});


Route::group(['middleware' => 'auth', 'prefix' => 'access'],function () {

    Route::get('/', 'AccessController@lists')
        ->name('access_lists');

    Route::get('/new', 'AccessController@show')
        ->name('access_show');

    Route::post('/new', 'AccessController@create')
        ->name('access_add');

    Route::get('/edit/{id}', 'AccessController@edit')
        ->name('access_edit');

    Route::post('/edit/{id}', 'AccessController@update')
        ->name('access_update');

    Route::get('/delete/{id}', 'AccessController@delete')
        ->name('access_delete');

    Route::post('/delete/{id}', 'AccessController@destroy')
        ->name('access_destroy');

});

Route::group(['middleware' => 'auth', 'prefix' => 'ga'],function () {

    Route::get('/', 'GoogleAnalyticsController@index')->name('google_analytics');

    Route::post('/ajaxInit', 'GoogleAnalyticsController@ajaxInitial')->name('ga_ajax_init');

});

Route::group(['middleware' => 'auth', 'prefix' => 'settings'],function () {

     Route::get('/', 'SettingsController@index')->name('settings_info');

});


 /**
     * Invoice segments
     */
    Route::group(['prefix' => 'invoice'],function () {

        

        Route::get('/', 'InvoiceController@lists')
            ->name('invoice_list');
        Route::get('/{id}/download', 'InvoiceController@download')
            ->name('invoice_download');
        Route::get('/{id}/info', 'InvoiceController@info')
            ->name('invoice_info');

        Route::get('/payment/status/{id}', 'PaymentController@getPaymentStatus')
            ->name('payment_status');
        Route::post('/payment/paypal', 'PaymentController@payWithpaypal')
            ->name('payment_paypal');

        Route::get('/subscription', 'InvoiceController@subscriptionInfo')
            ->name('payment_detail');

        Route::post('/savereceiptemail', 'InvoiceController@saveRecieptEmail')
            ->name('save_receiptemail');

       
        Route::get('/payment/savemethods', 'InvoiceController@show')
            ->name('show_payment_methods');

        Route::get('/paynow/{id}', 'InvoiceController@nonSubscriptionPayments')
            ->name('non_subscribe_payments');

        Route::get('/payment/methods/edit/{id}', 'InvoiceController@editPaymentMethod')
        ->name('payment_methods_edit');

        Route::post('/payment/methods/edit/{id}', 'ComPaymentController@updatePaymentMethod')
        ->name('payment_methods_update');


        Route::get('/payment/methods/{id}/delete', 'InvoiceController@deletePaymentMethod')
    ->name('payment_methods_delete_model');

    Route::post('payment/methods/{id}/delete', 'InvoiceController@removePaymentMethod')
    ->name('payment_methods_delete');


     Route::post('/payment/comweb', 'ComPaymentController@pay')
            ->name('payment_com');

      Route::get('/payment/savecard', 'ComPaymentController@savetoken')
            ->name('payment_com_savecc');

    Route::post('/payment/methods', 'ComPaymentController@savePaymentMethod')
            ->name('save_payment_methods');

        /*    Route::post('/payment/methods', 'InvoiceController@savePaymentMethod')
            ->name('save_payment_methods');*/


            Route::get('/receiptmail/delete/{id}', 'InvoiceController@deleteRecieptEmail')
            ->name('del_recieptmail');

               Route::post('/receiptmail/delete/{id}', 'InvoiceController@remove')
            ->name('remove_recieptmail');

             Route::get('/receiptmail/edit/{id}', 'InvoiceController@editRecieptEmail')
            ->name('edit_recieptmail');

              Route::post('/receiptmail/edit/{id}', 'InvoiceController@updateRecieptEmail')
            ->name('update_recieptmail');

             Route::get('/payment/method/default/{id}', 'InvoiceController@updateDefultPaymentMethod')
            ->name('payment_markdefault');

              Route::get('/payment/method/autopay/{id}/{auto_pay}', 'InvoiceController@updateAutoPay')
            ->name('invoice_autopay');

              Route::get('/autopay/{id}/{auto_pay}', 'InvoiceController@updateAutoPayInvoice')
            ->name('invoice_updateautopay');




    });

     Route::group(['middleware' => 'auth', 'prefix' => 'webanalytics'],function () {
    
     Route::get('/', 'WebAnalyticsController@index')->name('webanalytics');
     Route::get('/info/{view_id}', 'WebAnalyticsController@info')->name('webanalytics_info');
     Route::get('/datainfo', 'WebAnalyticsController@visitors')->name('datainfo');
     Route::get('/bounceRate', 'WebAnalyticsController@bounceRate')->name('bounceRate');
     Route::get('/sessionsInfo', 'WebAnalyticsController@sessionsInfo')->name('sessionsInfo');
     Route::get('/sessionsByChannelInfo', 'WebAnalyticsController@sessionsByChannelInfo')->name('sessionsByChannelInfo');
     Route::get('/sessionRate', 'WebAnalyticsController@newSessionsRateInfo')->name('sessionRate');
     Route::get('/audienceView', 'WebAnalyticsController@audienceView')->name('audienceView');
     Route::get('/topPageViews', 'WebAnalyticsController@topPageViews')->name('topPageViews');
     Route::get('/pageViewsInfo', 'WebAnalyticsController@pageViewsInfo')->name('pageViewsInfo');
     Route::get('/visitsByDevice', 'WebAnalyticsController@visitsByDevice')->name('visitsByDevice');
     Route::get('/visitsByCountries', 'WebAnalyticsController@visitsByCountries')->name('visitsByCountries');
      Route::get('/goalInfo', 'WebAnalyticsController@goalInfo')->name('goalInfo');
      

});

      Route::group(['middleware' => 'auth', 'prefix' => 'users'],function () {
          Route::get('/', 'EmployeeController@lists')->name('users_list');
          Route::get('/new', 'EmployeeController@show')->name('employee_modal');
          Route::post('/', 'EmployeeController@create')->name('employee_create');
          Route::get('/{id}/edit', 'EmployeeController@edit')->name('employee_edit_modal');

    Route::post('/{id}/edit', 'EmployeeController@update')->name('employee_edit');

    Route::get('/{id}/delete', 'EmployeeController@delete')->name('employee_delete_modal');

    Route::post('/{id}/delete', 'EmployeeController@remove')->name('employee_delete');
     });


      Route::group(['middleware' => 'auth', 'prefix' => 'semrush'],function () {
        Route::get('/siteaudit/{projectid}', 'SemrushController@index')->name('semrush_site_audit');
        Route::get('/siteaudit/issues/{projectid}', 'SemrushController@allIssues')->name('semrush_site_audit_issues');
        Route::get('/competitor-analysis/{projectid}', 'SemrushController@compatiterAnalysis')->name('semrush_competitor_analysis');

      });


       Route::group(['middleware' => 'auth', 'prefix' => 'proposal'],function () {
          Route::get('/{projectid}', 'ProposalController@download')->name('client_marketing_proposal');
         

      });

app/Models/Invoice.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Invoice extends Model
{
    protected $prefix =  "JPLMS";
    protected $fillable = [
        "client_id",
        "invoice_date",
        "due_date",
        "version",
        "terms",
        "parent_id",
        "gst_exp",
        "status",
        "payment_method",
        "schedule_date",
        "transaction_id",
        'card_fee',
        'late_charges',
        'auto_pay',
    ];

    public function setParentId()
    {
        $this->parent_id = $this->id;
        $this->save();
    }

    public function getNoAttribute()
    {
        $id = str_pad($this->parent_id, 5, '0', STR_PAD_LEFT);
        return $this->prefix.$id.numbers_to_chars($this->version);
    }

    public function client()
    {
        return $this->belongsTo(Client::class);
    }

    public function parent()
    {
        return $this->belongsTo(Invoice::class, 'parent_id');
    }

    public function creditNotes()
    {
        return $this->hasMany(CreditNote::class);
    }

    public function details()
    {
        
        return $this->hasMany(InvoiceDetails::class);
    }

    public function getBalanceAttribute()
    {
        $paid = $this->parent->creditNotes->sum('amount');
        $gst = $this->parent->creditNotes->sum('gst');
        return $this->total['total']-($paid+$gst);
    }
    public function getDepositAttribute()
    {
        $paid = $this->parent->creditNotes->sum('amount');
        $gst = $this->parent->creditNotes->sum('gst');
        return $paid+$gst;
    }

    public function getTotalAttribute()
    {
        $subtotal = $this->details->sum('amount');
        $gst = $this->details->sum('gst');

        $gst = $this->gst_exp!=1?$gst:0;
        $total = $subtotal+$gst;
        return compact('subtotal','gst','total','paid');
    }

    public function getNextVersion($id)
    {
        if ($id == 0) {
            return 0;
        }
        $invoice = $this->find($id);
        return $invoice->version+1;
    }

    public function history()
    {
        return $this->hasMany(Logger::class, "resource_id")
            ->where('type', 'invoice');
    }

    public function getMonthlyInvoices($year, $month)
    {
        return $this->whereMonth('invoice_date', $month)
                     ->whereYear('invoice_date', $year)
                     ->where('status','PAID');
                    

    }

    public function getMonthlyAllInvoices($year, $month)
    {
        return $this->whereMonth('invoice_date', $month)
                     ->whereYear('invoice_date', $year);
    }


     public function getMaxVersionInvoice( $id)
    {
        return $this->where('parent_id',$id)
               ->max('id');
    }
    


    //get client monthly paid invoices
   /* public function getClientMonthlyInvoices($clientId, $year, $month)
    {
        return $this->whereMonth('invoice_date', $month)
                     ->whereYear('invoice_date', $year)
                     ->where('client_id', $clientId)
                     ->where('status','PAID')
                      ->where('is_reconcile',0);
                    

    }*/

    
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;


use Auth;
use App\Models\Logger;
use App\Models\Client;
use App\Models\EmailAddress;
use App\Services\UserService;
use App\Services\ClientService;
use App\Services\AccessService;
use App\Services\JobService;
use App\Services\InvoiceManager;
use Facades\App\Foundation\Modal\Modal;
use Facades\App\Foundation\Modal\ModalMessage;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
	 /**
     * @var EmailAddress
     */
    private $emailAddress;

    private $userService;

    private $accessService;

    private $jobService;

    private $invoiceManager;

    public function __construct(EmailAddress $emailAddress, UserService $userService, AccessService $accessService, JobService $jobService, InvoiceManager $invoiceManager,ClientService $clientService)
    {
       $this->emailAddress   = $emailAddress;
       $this->userService    = $userService;
       $this->accessService  = $accessService;
       $this->jobService     = $jobService;
       $this->invoiceManager = $invoiceManager;
       $this->clientService = $clientService;
  
    }


    public function index( )
    {
        $client             = $this->getClient();

       if ( $client == null)
       { 
              return redirect('/logout');
       }

        $employees          = $this->userService->employees($client->id)->take(5);
        $emailAddresses     = $this->emailAddress->take(5)->where('client_id', $client->id)->get();
        $access             = $this->accessService->firstRecord($client->id);
        $jobs               = $this->jobService->activeJobs()->take(5);
        $invoices           = $this->invoiceManager->lists()->where('status','UNPAID')->take(3);
      
    	return view('dashboard.index')->with(compact('client','employees','emailAddresses','access','jobs','invoices'));
      
    }

    function getClient()
    {
        if ( Auth::user()->role == 'admin')
       {

            $client_id = session('client_id');
            $client    = Client::find( $client_id);
          
       }else
       {
             $client  = Client::find(Auth::user()->client_id);
             
       }
       return $client;
      
    }


    //save card info in db
     public function showAddEmail()
    {
        $client = $this->getClient();

        return Modal::create()
            ->title("Add an access")
            ->template('modal.forms.email-address-list')
            ->buttons(["Create", "Cancel"])
            ->variables(compact('client'))
            ->render();
    }

	 public function saveEmailAddress(Request $request)
    {
         $attributes = $request->all();
  

         $emailAddress = new EmailAddress();
         $emailAddress->create($attributes);
        return ModalMessage::success("Email Address successfully saved!");

     

    }

    public function emailList()
    {
    	$client = $this->getClient();
        $emailAddresses = $this->emailAddress->where('client_id', $client->id)->get();
        return view('pages.email_addresses_list')
                ->with(compact('emailAddresses'));
    }


    //update client info
     public function editClient()
    {
        $client = $this->getClient();

        return Modal::create()
            ->title("Add an access")
            ->template('modal.forms.client-edit')
            ->buttons(["Create", "Cancel"])
            ->variables(compact('client'))
            ->render();
    }

     public function updateClient(Request $request)
    {
        $client     = $this->getClient();
        $attributes = $request->all();
        $this->clientService->update($client->id,$attributes);

        return ModalMessage::success("Client updated successfully saved!");

     

    }
}

resources/views/dashboard/index.blade.php
@extends('layouts.app')


@section('content')
<div id="wrapper" class="client-dashboard">
 <section id="page-content-wrapper">
    <div class="container-wrapper container-fuild">
      <div class="row">
        <div class="col-sm-12">
          <div class="row clients">
            <div class="col-sm-12">
              <h2>Dashboard</h2>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
              <p>Welcome,  {{ Auth::user()->name }}</p>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-4">
              <section class="content">
                <fieldset class="profile">
                  <div class="row">
                    <div class="col-md-12"> <a href="#" class="pull-right"
                   data-modal-uri="{{ route('edit_client') }}" id="edit-client" style="margin-right: 10px"><i class="fa fa-pencil-square-o" aria-hidden="true" title="Edit"></i>Edit Info</a> </div>
                    <div class="col-md-12"> <img src="http://pm.jplms.com.au/images/{{ $client->logo }}" alt="" width="150"> </div>
                  </div>
                  <div class="row">
                    <label class="col-md-6">Company Name</label>
                    <div class="col-md-6">{{ $client->company_name }}</div>
                  </div>
                  <div class="row">
                    <label class="col-md-6">ABN</label>
                    <div class="col-md-6">{{ $client->abn }}</div>
                  </div>
                  <div class="row">
                    <label class="col-md-6">Address</label>
                    <div class="col-md-6">{{ $client->address }} {{ $client->street }}  {{ $client->subrub }}  {{ $client->state }}</div>
                  </div>
                  <div class="row">
                    <label class="col-md-6">Primary Accounts</label>
                    <div class="col-md-6">xxxxx</div>
                  </div>
                </fieldset>
              </section>
            </div>
            <div class="col-md-4">
              <section class="content">
                <fieldset class="make-payment">
                  <label>Make a Payment</label>
                   <table class="table table-striped">
                    <tbody>
                      @foreach( $invoices as $invoice)
                      <tr>
                        <td>{{ $invoice->no }}</td>
                        <td class="text-right">{{--&#36;150.50--}}</td>
                        <td><a href="{{route('non_subscribe_payments', $invoice->id)}}"><button class="btn btn-sm btn-danger">Pay Now</button></a></td>
                      </tr>
                      @endforeach
                     
                    </tbody>
                  </table>
                </fieldset>
              </section>
              <section class="content">
                <fieldset class="support-request">
                   <label>Support Request</label>
                             <table class="table table-bordered table-hover in-progress">
                <tbody>
                  @foreach ( $jobs as $job)
                  <tr>
                    <td><strong>{{ $job->code }}
                      @foreach (  $job->assignees as $assignee )
                        <mark>[{{ $assignee->name}}]</mark>
                      @endforeach
                      </strong> <br>
                      <span>{{ str_limit($job->title, 33) }} </span>
                      <aside class="action">
                        <a href="task-job-update.html"><i class="fa fa-cog" aria-hidden="true"></i></a><a href="#"><i class="fa fa-trash" aria-hidden="true"></i></a>
                        <small>
                          {{ date('m/d/Y',strtotime($job->due_date)) }}
                        </small>
                        </aside>
                        <div class="priority high" aria-hidden="true" data-toggle="tooltip" data-placement="right" title="" data-original-title="{{ ucwords($job->priority) }}"></div>
                        </td>
                  </tr>
                   @endforeach
                  
                </tbody>
              </table>
                    <a href="#" class="btn btn-default pull-right"
                   data-modal-uri="{{ route('job_modal') }}" id="add-job" style="margin-right: 10px"><i class="fa fa-plus" aria-hidden="true"></i> Add New Request</a>
                </fieldset>
              </section>
            </div>
            <div class="col-md-4">
              <section class="content">
                <fieldset class="ms-sign">
                  <a href="https://login.live.com/" target="_blank"><img src="{{ asset('images/microsoft-sign-in.jpg') }}" alt=""></a>
                </fieldset>
              </section>
            </div>
          </div>
          <div class="row access">
            <div class="col-md-4">
              <section class="content">
                <fieldset>
                  <table class="table table-striped table-hover">
                    <tbody>
                      <tr>
                        <th scope="col">Name</th>
                        <th scope="col"></th>
                      </tr>
                      @foreach ($employees as $employee)
                      <tr>
                        <td>{{ $employee->name }}</td>
                        <td><a href="#" data-modal-uri="{{ route('employee_delete_modal', $employee->id )}}"  class="pull-right delete-employee"><i class="fa fa-trash-o" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Delete"></i></a>&nbsp;&nbsp;<a href="#" data-modal-uri="{{ route('employee_edit_modal', $employee->id ) }}"  class="pull-right edit-employee"><i class="fa fa-pencil-square-o" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Edit"></i></a>
                        </td>
                      </tr>
                      @endforeach
                    </tbody>
                  </table>
                </fieldset>
              </section>
            </div>
            <div class="col-md-4">
              <section class="content">
                <fieldset>
                  <table class="table table-striped table-hover">
                    <tbody>
                      <tr>
                        <th scope="col">Email</th>
                        <th scope="col"><i class="fa fa-lock" aria-hidden="true"></i></th>
                      </tr>
                      @foreach ($emailAddresses as $address)
                      <tr>
                        <td>{{ $address->email}}</td>
                        <td><strong><input type="password" value="{{ $address->password }}" style="border: none; background-color: transparent" class="pwd"></strong> <a href="#" class="pull-right show"><i class="fa fa-eye" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Reveal"></i></a></td>
                      </tr>
                     @endforeach
                    </tbody>
                  </table>
                </fieldset>
              </section>
            </div>
            <div class="col-md-4">
              <section class="content">
                <fieldset>
                  @if (  $access)
                  <table class="table table-striped table-hover">
                    <tbody>
                      <tr>
                        <td class="icon"><a href="task-detailed-view-pa.html"><i class="fa fa-building-o" aria-hidden="true"></i></a></td>
                        <td><strong>{{ $access->organization }}</strong> <a href="#" data-modal-uri="{{ route('access_delete', $access->id) }}" class="pull-right delete-access"><i class="fa fa-trash-o" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Delete"></i></a>&nbsp;&nbsp;<a href="#" data-modal-uri="{{ route('access_edit', $access->id) }}" class="pull-right edit-access"><i class="fa fa-pencil-square-o" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Edit"></i></a></td>
                      </tr>
                      <tr>
                        <td class="icon"><a href="task-detailed-view-pa.html"><i class="fa fa-address-card-o" aria-hidden="true"></i></a></td>
                        <td>{{ $access->ref_number }}</td>
                      </tr>
                      <tr>
                        <td class="icon"><a href="task-detailed-view-pa.html"><i class="fa fa-user-circle" aria-hidden="true"></i></a></td>
                        <td>{{ $access->username }}</td>
                      </tr>
                      <tr>
                        <td class="icon"><a href="task-detailed-view-pa.html"><i class="fa fa-lock" aria-hidden="true"></i></a></td>
                       <td><strong><input type="password" value="{{ $access->password }}" style="border: none; background-color: transparent" class="pwd"></strong>
                                    <a href="#" class="pull-right show">
                                        <i class="fa fa-eye" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Reveal"></i>
                                    </a>
                                </td>
                      </tr>
                      <tr>
                        <td class="icon"><a href="task-detailed-view-pa.html"><i class="fa fa-th" aria-hidden="true"></i></a></td>
                       <td><strong><input type="password" value="{{ $access->pin }}" style="border: none; background-color: transparent" class="pwd"></strong>
                                    <a href="#" class="pull-right show">
                                        <i class="fa fa-eye" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Reveal"></i>
                                    </a>
                                </td>
                      </tr>
                    </tbody>
                  </table>
                  @endif
                </fieldset>
              </section>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-4">
              <div class="lg-tab"> <a href="#" data-toggle="modal" data-modal-uri="{{ route('employee_modal') }}"  id="add-user" class="lg"><i class="fa fa-plus" aria-hidden="true"></i> ADD <span>User</span></a>
                <div><a href="{{ route('users_list')}}"><i class="fa fa-list" aria-hidden="true"></i>&nbsp;&nbsp;VIEW ALL</a></div>
              </div>
            </div>
            <div class="col-sm-4">
              <div class="lg-tab"> <a href="#" data-toggle="modal" data-modal-uri="{{ route('emai_address_add_form') }}"  id="add-email" class="lg"><i class="fa fa-plus" aria-hidden="true"></i> ADD <span>Email Address</span></a>
                <div><a href="{{ route('emai_address_list') }}"><i class="fa fa-list" aria-hidden="true"></i>&nbsp;&nbsp;VIEW ALL</a></div>
              </div>
            </div>
            <div class="col-sm-4">
              <div class="lg-tab"> <a href="#" data-toggle="modal"  data-modal-uri="{{ route('access_show') }}"  id="add-access" class="lg"><i class="fa fa-plus" aria-hidden="true"></i> ADD <span>Access</span></a>
                <div><a href="{{ route('access_lists') }}"><i class="fa fa-list" aria-hidden="true"></i>&nbsp;&nbsp;VIEW ALL</a></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

@endsection

@section('scripts')
  <script>
        $(document).ready(function () {
            $('#add-access').modalRender();
            $('#add-email').modalRender();
            $('#add-user').modalRender();
            $('#add-job').modalRender();
             $('#edit-client').modalRender();

               $('.edit-employee').modalRender();
            $('.delete-employee').modalRender();

               $('.delete-access').modalRender();
            $('.edit-access').modalRender();

                $('.show').click(function () {
                var el = $(this).parent().find('.pwd');
                if (el.get(0).type === "password") {
                    el.get(0).type = "text";

                    return false;
                } else {
                    el.get(0).type = "password";

                    return false;
                }
            });

  });
    </script>
@endsection